# Generated by Django 3.2.8 on 2021-10-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
