# Generated by Django 3.2.8 on 2021-10-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_travel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
