# Generated by Django 3.2.8 on 2021-10-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_travel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
